FROM ubuntu:16.04

RUN apt-get update && apt-get install -y openssh-server
RUN mkdir /var/run/sshd
RUN echo 'root:screencast' | chpasswd															## TAKE OUT
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config		## TAKE OUT
RUN sed -i 's/Port 22/Port 22\nPort 3122/g' /etc/ssh/sshd_config
RUN echo 'Ciphers chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,arcfour' >> /etc/ssh/sshd_config
RUN echo 'MACs hmac-sha2-512,hmac-sha1,hmac-ripemd160' >> /etc/ssh/sshd_config
RUN sed -i '/HostKey \/etc\/ssh\/ssh_host_dsa_key/d' /etc/ssh/sshd_config
RUN sed -i '/HostKey \/etc\/ssh\/ssh_host_rsa_key/d' /etc/ssh/sshd_config
RUN sed -i '/HostKey \/etc\/ssh\/ssh_host_ed25519_key/d' /etc/ssh/sshd_config

# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
