<?php
// This script and data application were generated by AppGini 5.41
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/computers.php");
	include("$currDir/computers_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('computers');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "computers";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`computers`.`id`" => "id",
		"`computers`.`blueskyid`" => "blueskyid",
		"`computers`.`serialnum`" => "serialnum",
		"`computers`.`hostname`" => "hostname",
		"`computers`.`sshlink`" => "sshlink",
		"`computers`.`vnclink`" => "vnclink",
		"`computers`.`scplink`" => "scplink",
		"`computers`.`username`" => "username",
		"`computers`.`sharingname`" => "sharingname",
		"`computers`.`gruntwork`" => "gruntwork",
		"`computers`.`datetime`" => "datetime",
		"`computers`.`status`" => "status",
		"`computers`.`registered`" => "registered",
		"concat('<img src=\"', if(`computers`.`notify`, 'checked.gif', 'checkednot.gif'), '\" border=\"0\" />')" => "notify",
		"concat('<img src=\"', if(`computers`.`alert`, 'checked.gif', 'checkednot.gif'), '\" border=\"0\" />')" => "alert",
		"`computers`.`email`" => "email",
		"`computers`.`notes`" => "notes",
		"concat('<img src=\"', if(`computers`.`selfdestruct`, 'checked.gif', 'checkednot.gif'), '\" border=\"0\" />')" => "selfdestruct",
		"concat('<img src=\"', if(`computers`.`downup`, 'checked.gif', 'checkednot.gif'), '\" border=\"0\" />')" => "downup",
		"`computers`.`timestamp`" => "timestamp"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`computers`.`id`',
		2 => '`computers`.`blueskyid`',
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
		10 => 10,
		11 => 11,
		12 => 12,
		13 => 13,
		14 => '`computers`.`notify`',
		15 => '`computers`.`alert`',
		16 => 16,
		17 => 17,
		18 => '`computers`.`selfdestruct`',
		19 => '`computers`.`downup`',
		20 => 20
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`computers`.`id`" => "id",
		"`computers`.`blueskyid`" => "blueskyid",
		"`computers`.`serialnum`" => "serialnum",
		"`computers`.`hostname`" => "hostname",
		"`computers`.`sshlink`" => "sshlink",
		"`computers`.`vnclink`" => "vnclink",
		"`computers`.`scplink`" => "scplink",
		"`computers`.`username`" => "username",
		"`computers`.`sharingname`" => "sharingname",
		"`computers`.`gruntwork`" => "gruntwork",
		"`computers`.`datetime`" => "datetime",
		"`computers`.`status`" => "status",
		"`computers`.`registered`" => "registered",
		"`computers`.`notify`" => "notify",
		"`computers`.`alert`" => "alert",
		"`computers`.`email`" => "email",
		"`computers`.`notes`" => "notes",
		"`computers`.`selfdestruct`" => "selfdestruct",
		"`computers`.`downup`" => "downup",
		"`computers`.`timestamp`" => "timestamp"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(   
		"`computers`.`id`" => "ID",
		"`computers`.`blueskyid`" => "BlueSky ID",
		"`computers`.`serialnum`" => "Serial Number",
		"`computers`.`hostname`" => "Name",
		"`computers`.`sshlink`" => "SSH",
		"`computers`.`vnclink`" => "VNC",
		"`computers`.`scplink`" => "SCP",
		"`computers`.`username`" => "UserName",
		"`computers`.`sharingname`" => "Sharing Name",
		"`computers`.`gruntwork`" => "Gruntwork Link",
		"`computers`.`datetime`" => "Last Check In",
		"`computers`.`status`" => "Status",
		"`computers`.`registered`" => "Registration Time",
		"`computers`.`notify`" => "Notify",
		"`computers`.`alert`" => "Alert",
		"`computers`.`email`" => "Email Address to Notify",
		"`computers`.`notes`" => "Notes",
		"`computers`.`selfdestruct`" => "Remove BlueSky (Cannot Undo From Here)",
		"`computers`.`downup`" => "Downup",
		"`computers`.`timestamp`" => "Timestamp"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`computers`.`id`" => "id",
		"`computers`.`blueskyid`" => "blueskyid",
		"`computers`.`serialnum`" => "serialnum",
		"`computers`.`hostname`" => "hostname",
		"`computers`.`sshlink`" => "sshlink",
		"`computers`.`vnclink`" => "vnclink",
		"`computers`.`scplink`" => "scplink",
		"`computers`.`username`" => "username",
		"`computers`.`sharingname`" => "sharingname",
		"`computers`.`gruntwork`" => "gruntwork",
		"`computers`.`datetime`" => "datetime",
		"`computers`.`status`" => "status",
		"`computers`.`registered`" => "registered",
		"concat('<img src=\"', if(`computers`.`notify`, 'checked.gif', 'checkednot.gif'), '\" border=\"0\" />')" => "notify",
		"concat('<img src=\"', if(`computers`.`alert`, 'checked.gif', 'checkednot.gif'), '\" border=\"0\" />')" => "alert",
		"`computers`.`email`" => "email",
		"`computers`.`notes`" => "notes",
		"concat('<img src=\"', if(`computers`.`selfdestruct`, 'checked.gif', 'checkednot.gif'), '\" border=\"0\" />')" => "selfdestruct",
		"concat('<img src=\"', if(`computers`.`downup`, 'checked.gif', 'checkednot.gif'), '\" border=\"0\" />')" => "downup",
		"`computers`.`timestamp`" => "timestamp"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom="`computers` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 1;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 100;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "computers_view.php";
	$x->RedirectAfterInsert = "computers_view.php";
	$x->TableTitle = "BlueSky Admin";
	$x->TableIcon = "table.gif";
	$x->PrimaryKey = "`computers`.`id`";

	$x->ColWidth   = array(  85, 230, 150, 150, 150, 150, 150, 150, 50, 50);
	$x->ColCaption = array("BlueSky ID", "Serial Number", "Name", "SSH", "VNC", "SCP", "Last Check In", "Status", "Notify", "Alert");
	$x->ColFieldName = array('blueskyid', 'serialnum', 'hostname', 'sshlink', 'vnclink', 'scplink', 'datetime', 'status', 'notify', 'alert');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 11, 12, 14, 15);

	$x->Template = 'templates/computers_templateTV.html';
	$x->SelectedTemplate = 'templates/computers_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `computers`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='computers' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `computers`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='computers' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`computers`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: computers_init
	$render=TRUE;
	if(function_exists('computers_init')){
		$args=array();
		$render=computers_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: computers_header
	$headerCode='';
	if(function_exists('computers_header')){
		$args=array();
		$headerCode=computers_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: computers_footer
	$footerCode='';
	if(function_exists('computers_footer')){
		$args=array();
		$footerCode=computers_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>