<?php

// Data functions (insert, update, delete, form) for table computers

// This script and data application were generated by AppGini 5.41
// Download AppGini for free from http://bigprof.com/appgini/download/

function computers_insert(){
	global $Translation;

	if($_GET['insert_x']!=''){$_POST=$_GET;}

	// mm: can member insert record?
	$arrPerm=getTablePermissions('computers');
	if(!$arrPerm[1]){
		return false;
	}

	$data['blueskyid'] = makeSafe($_POST['blueskyid']);
		if($data['blueskyid'] == empty_lookup_value){ $data['blueskyid'] = ''; }
	$data['hostname'] = makeSafe($_POST['hostname']);
		if($data['hostname'] == empty_lookup_value){ $data['hostname'] = ''; }
	$data['username'] = makeSafe($_POST['username']);
		if($data['username'] == empty_lookup_value){ $data['username'] = ''; }
	$data['notify'] = makeSafe($_POST['notify']);
		if($data['notify'] == empty_lookup_value){ $data['notify'] = ''; }
	$data['alert'] = makeSafe($_POST['alert']);
		if($data['alert'] == empty_lookup_value){ $data['alert'] = ''; }
	$data['email'] = makeSafe($_POST['email']);
		if($data['email'] == empty_lookup_value){ $data['email'] = ''; }
	$data['notes'] = br2nl(makeSafe($_POST['notes']));
	$data['selfdestruct'] = makeSafe($_POST['selfdestruct']);
		if($data['selfdestruct'] == empty_lookup_value){ $data['selfdestruct'] = ''; }
	if($data['blueskyid']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'BlueSky ID': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}

	// hook: computers_before_insert
	if(function_exists('computers_before_insert')){
		$args=array();
		if(!computers_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('insert into `computers` set       `blueskyid`=' . (($data['blueskyid'] !== '' && $data['blueskyid'] !== NULL) ? "'{$data['blueskyid']}'" : 'NULL') . ', `hostname`=' . (($data['hostname'] !== '' && $data['hostname'] !== NULL) ? "'{$data['hostname']}'" : 'NULL') . ', `username`=' . (($data['username'] !== '' && $data['username'] !== NULL) ? "'{$data['username']}'" : 'NULL') . ', `notify`=' . (($data['notify'] !== '' && $data['notify'] !== NULL) ? "'{$data['notify']}'" : 'NULL') . ', `alert`=' . (($data['alert'] !== '' && $data['alert'] !== NULL) ? "'{$data['alert']}'" : 'NULL') . ', `email`=' . (($data['email'] !== '' && $data['email'] !== NULL) ? "'{$data['email']}'" : 'NULL') . ', `notes`=' . (($data['notes'] !== '' && $data['notes'] !== NULL) ? "'{$data['notes']}'" : 'NULL') . ', `selfdestruct`=' . (($data['selfdestruct'] !== '' && $data['selfdestruct'] !== NULL) ? "'{$data['selfdestruct']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"computers_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID=db_insert_id(db_link());

	// hook: computers_after_insert
	if(function_exists('computers_after_insert')){
		$res = sql("select * from `computers` where `id`='" . makeSafe($recID) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID);
		$args=array();
		if(!computers_after_insert($data, getMemberInfo(), $args)){ return (get_magic_quotes_gpc() ? stripslashes($recID) : $recID); }
	}

	// mm: save ownership data
	sql("insert into membership_userrecords set tableName='computers', pkValue='$recID', memberID='".getLoggedMemberID()."', dateAdded='".time()."', dateUpdated='".time()."', groupID='".getLoggedGroupID()."'", $eo);

	return (get_magic_quotes_gpc() ? stripslashes($recID) : $recID);
}

function computers_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('computers');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='computers' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='computers' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: computers_before_delete
	if(function_exists('computers_before_delete')){
		$args=array();
		if(!computers_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	sql("delete from `computers` where `id`='$selected_id'", $eo);

	// hook: computers_after_delete
	if(function_exists('computers_after_delete')){
		$args=array();
		computers_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='computers' and pkValue='$selected_id'", $eo);
}

function computers_update($selected_id){
	global $Translation;

	if($_GET['update_x']!=''){$_POST=$_GET;}

	// mm: can member edit record?
	$arrPerm=getTablePermissions('computers');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='computers' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='computers' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['blueskyid'] = makeSafe($_POST['blueskyid']);
		if($data['blueskyid'] == empty_lookup_value){ $data['blueskyid'] = ''; }
	if($data['blueskyid']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'BlueSky ID': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['hostname'] = makeSafe($_POST['hostname']);
		if($data['hostname'] == empty_lookup_value){ $data['hostname'] = ''; }
	$data['username'] = makeSafe($_POST['username']);
		if($data['username'] == empty_lookup_value){ $data['username'] = ''; }
	$data['notify'] = makeSafe($_POST['notify']);
		if($data['notify'] == empty_lookup_value){ $data['notify'] = ''; }
	$data['alert'] = makeSafe($_POST['alert']);
		if($data['alert'] == empty_lookup_value){ $data['alert'] = ''; }
	$data['email'] = makeSafe($_POST['email']);
		if($data['email'] == empty_lookup_value){ $data['email'] = ''; }
	$data['notes'] = br2nl(makeSafe($_POST['notes']));
	$data['selfdestruct'] = makeSafe($_POST['selfdestruct']);
		if($data['selfdestruct'] == empty_lookup_value){ $data['selfdestruct'] = ''; }
	$data['selectedID']=makeSafe($selected_id);

	// hook: computers_before_update
	if(function_exists('computers_before_update')){
		$args=array();
		if(!computers_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `computers` set       `blueskyid`=' . (($data['blueskyid'] !== '' && $data['blueskyid'] !== NULL) ? "'{$data['blueskyid']}'" : 'NULL') . ', `hostname`=' . (($data['hostname'] !== '' && $data['hostname'] !== NULL) ? "'{$data['hostname']}'" : 'NULL') . ', `username`=' . (($data['username'] !== '' && $data['username'] !== NULL) ? "'{$data['username']}'" : 'NULL') . ', `notify`=' . (($data['notify'] !== '' && $data['notify'] !== NULL) ? "'{$data['notify']}'" : 'NULL') . ', `alert`=' . (($data['alert'] !== '' && $data['alert'] !== NULL) ? "'{$data['alert']}'" : 'NULL') . ', `email`=' . (($data['email'] !== '' && $data['email'] !== NULL) ? "'{$data['email']}'" : 'NULL') . ', `notes`=' . (($data['notes'] !== '' && $data['notes'] !== NULL) ? "'{$data['notes']}'" : 'NULL') . ', `selfdestruct`=' . (($data['selfdestruct'] !== '' && $data['selfdestruct'] !== NULL) ? "'{$data['selfdestruct']}'" : 'NULL') . " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="computers_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: computers_after_update
	if(function_exists('computers_after_update')){
		$res = sql("SELECT * FROM `computers` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!computers_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='computers' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function computers_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('computers');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}


	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='computers' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='computers' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `computers` where `id`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found']);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
	}else{
	}

	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$templateCode = @file_get_contents('./templates/computers_templateDVP.html');
	}else{
		$templateCode = @file_get_contents('./templates/computers_templateDV.html');
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'BlueSky Admin', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($arrPerm[1] && !$selected_id){ // allow insert and no record selected?
		if(!$selected_id) $templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return computers_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return computers_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'window.parent.jQuery(\'.modal\').modal(\'hide\'); return false;';
	}else{
		$backAction = '$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode=str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return computers_validateData();"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#blueskyid').replaceWith('<div class=\"form-control-static\" id=\"blueskyid\">' + (jQuery('#blueskyid').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#hostname').replaceWith('<div class=\"form-control-static\" id=\"hostname\">' + (jQuery('#hostname').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#username').replaceWith('<div class=\"form-control-static\" id=\"username\">' + (jQuery('#username').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#notify').prop('disabled', true);\n";
		$jsReadOnly .= "\tjQuery('#alert').prop('disabled', true);\n";
		$jsReadOnly .= "\tjQuery('#email').replaceWith('<div class=\"form-control-static\" id=\"email\">' + (jQuery('#email').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#notes').replaceWith('<div class=\"form-control-static\" id=\"notes\">' + (jQuery('#notes').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#selfdestruct').prop('disabled', true);\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif(($AllowInsert && !$selected_id) || ($AllowUpdate && $selected_id)){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array();
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-lg" id="' . $ptfc[0] . '_view_parent" title="' . htmlspecialchars($Translation['View'] . ' ' . $ptfc[1], ENT_QUOTES, 'UTF-8') . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . htmlspecialchars($Translation['Add New'] . ' ' . $ptfc[1], ENT_QUOTES, 'UTF-8') . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode=str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(blueskyid)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(serialnum)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(hostname)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(sshlink)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(vnclink)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(scplink)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(username)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(sharingname)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(gruntwork)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(datetime)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(status)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(registered)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(notify)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(alert)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(email)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(notes)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(selfdestruct)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(downup)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(timestamp)%%>', '', $templateCode);

	// process values
	if($selected_id){
		$templateCode=str_replace('<%%VALUE(id)%%>', htmlspecialchars($row['id'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		$templateCode=str_replace('<%%VALUE(blueskyid)%%>', htmlspecialchars($row['blueskyid'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(blueskyid)%%>', urlencode($urow['blueskyid']), $templateCode);
		$templateCode=str_replace('<%%VALUE(serialnum)%%>', htmlspecialchars($row['serialnum'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(serialnum)%%>', urlencode($urow['serialnum']), $templateCode);
		$templateCode=str_replace('<%%VALUE(hostname)%%>', htmlspecialchars($row['hostname'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(hostname)%%>', urlencode($urow['hostname']), $templateCode);
		$templateCode=str_replace('<%%VALUE(sshlink)%%>', htmlspecialchars($row['sshlink'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(sshlink)%%>', urlencode($urow['sshlink']), $templateCode);
		$templateCode=str_replace('<%%VALUE(vnclink)%%>', htmlspecialchars($row['vnclink'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(vnclink)%%>', urlencode($urow['vnclink']), $templateCode);
		$templateCode=str_replace('<%%VALUE(scplink)%%>', htmlspecialchars($row['scplink'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(scplink)%%>', urlencode($urow['scplink']), $templateCode);
		$templateCode=str_replace('<%%VALUE(username)%%>', htmlspecialchars($row['username'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(username)%%>', urlencode($urow['username']), $templateCode);
		$templateCode=str_replace('<%%VALUE(sharingname)%%>', htmlspecialchars($row['sharingname'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(sharingname)%%>', urlencode($urow['sharingname']), $templateCode);
		if($AllowUpdate || $AllowInsert){
			$templateCode=str_replace('<%%HTMLAREA(gruntwork)%%>', '<textarea name="gruntwork" id="gruntwork" rows="5">'.htmlspecialchars($row['gruntwork'], ENT_QUOTES, 'UTF-8').'</textarea>', $templateCode);
		}else{
			$templateCode=str_replace('<%%HTMLAREA(gruntwork)%%>', $row['gruntwork'], $templateCode);
		}
		$templateCode=str_replace('<%%VALUE(gruntwork)%%>', nl2br($row['gruntwork']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(gruntwork)%%>', urlencode($urow['gruntwork']), $templateCode);
		$templateCode=str_replace('<%%VALUE(datetime)%%>', htmlspecialchars($row['datetime'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(datetime)%%>', urlencode($urow['datetime']), $templateCode);
		$templateCode=str_replace('<%%VALUE(status)%%>', htmlspecialchars($row['status'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(status)%%>', urlencode($urow['status']), $templateCode);
		$templateCode=str_replace('<%%VALUE(registered)%%>', htmlspecialchars($row['registered'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(registered)%%>', urlencode($urow['registered']), $templateCode);
		$templateCode=str_replace('<%%CHECKED(notify)%%>', ($row['notify'] ? "checked" : ""), $templateCode);
		$templateCode=str_replace('<%%CHECKED(alert)%%>', ($row['alert'] ? "checked" : ""), $templateCode);
		$templateCode=str_replace('<%%VALUE(email)%%>', htmlspecialchars($row['email'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(email)%%>', urlencode($urow['email']), $templateCode);
		if($dvprint){
			$templateCode = str_replace('<%%VALUE(notes)%%>', nl2br(htmlspecialchars($row['notes'], ENT_QUOTES, 'UTF-8')), $templateCode);
		}else{
			$templateCode = str_replace('<%%VALUE(notes)%%>', htmlspecialchars($row['notes'], ENT_QUOTES, 'UTF-8'), $templateCode);
		}
		$templateCode=str_replace('<%%URLVALUE(notes)%%>', urlencode($urow['notes']), $templateCode);
		$templateCode=str_replace('<%%CHECKED(selfdestruct)%%>', ($row['selfdestruct'] ? "checked" : ""), $templateCode);
		$templateCode=str_replace('<%%CHECKED(downup)%%>', ($row['downup'] ? "checked" : ""), $templateCode);
		$templateCode=str_replace('<%%VALUE(timestamp)%%>', htmlspecialchars($row['timestamp'], ENT_QUOTES, 'UTF-8'), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(timestamp)%%>', urlencode($urow['timestamp']), $templateCode);
	}else{
		$templateCode=str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(blueskyid)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(blueskyid)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(serialnum)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(serialnum)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(hostname)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(hostname)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(sshlink)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(sshlink)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(vnclink)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(vnclink)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(scplink)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(scplink)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(username)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(username)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(sharingname)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(sharingname)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%HTMLAREA(gruntwork)%%>', '<textarea name="gruntwork" id="gruntwork" rows="5"></textarea>', $templateCode);
		$templateCode=str_replace('<%%VALUE(datetime)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(datetime)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(status)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(status)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(registered)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(registered)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%CHECKED(notify)%%>', '', $templateCode);
		$templateCode=str_replace('<%%CHECKED(alert)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(email)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(email)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(notes)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(notes)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%CHECKED(selfdestruct)%%>', '', $templateCode);
		$templateCode=str_replace('<%%CHECKED(downup)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(timestamp)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(timestamp)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode=str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode=str_replace('<%%', '<!-- ', $templateCode);
	$templateCode=str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_POST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
			$templateCode.="\n\tif(document.getElementById('sshlinkEditLink')){ document.getElementById('sshlinkEditLink').style.display='none'; }";
			$templateCode.="\n\tif(document.getElementById('vnclinkEditLink')){ document.getElementById('vnclinkEditLink').style.display='none'; }";
			$templateCode.="\n\tif(document.getElementById('scplinkEditLink')){ document.getElementById('scplinkEditLink').style.display='none'; }";
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode=preg_replace('/blank.gif" rel="lightbox\[.*?\]"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	// hook: computers_dv
	if(function_exists('computers_dv')){
		$args=array();
		computers_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>