<?php
// This script and data application were generated by AppGini 5.41
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/connections.php");
	include("$currDir/connections_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('connections');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "connections";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`connections`.`id`" => "id",
		"`connections`.`timestamp`" => "timestamp",
		"`connections`.`sourceIP`" => "sourceIP",
		"`connections`.`adminkey`" => "adminkey",
		"`connections`.`targetPort`" => "targetPort",
		"`connections`.`exitStatus`" => "exitStatus",
		"`connections`.`startTime`" => "startTime",
		"`connections`.`endTime`" => "endTime",
		"`connections`.`notes`" => "notes"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`connections`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`connections`.`id`" => "id",
		"`connections`.`timestamp`" => "timestamp",
		"`connections`.`sourceIP`" => "sourceIP",
		"`connections`.`adminkey`" => "adminkey",
		"`connections`.`targetPort`" => "targetPort",
		"`connections`.`exitStatus`" => "exitStatus",
		"`connections`.`startTime`" => "startTime",
		"`connections`.`endTime`" => "endTime",
		"`connections`.`notes`" => "notes"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(   
		"`connections`.`id`" => "ID",
		"`connections`.`timestamp`" => "TimeStamp",
		"`connections`.`sourceIP`" => "Source IP",
		"`connections`.`adminkey`" => "Admin Key",
		"`connections`.`targetPort`" => "Target Port",
		"`connections`.`exitStatus`" => "Exit Status",
		"`connections`.`startTime`" => "Start Time",
		"`connections`.`endTime`" => "End Time",
		"`connections`.`notes`" => "Notes"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`connections`.`id`" => "id",
		"`connections`.`timestamp`" => "timestamp",
		"`connections`.`sourceIP`" => "sourceIP",
		"`connections`.`adminkey`" => "adminkey",
		"`connections`.`targetPort`" => "targetPort",
		"`connections`.`exitStatus`" => "exitStatus",
		"`connections`.`startTime`" => "startTime",
		"`connections`.`endTime`" => "endTime",
		"`connections`.`notes`" => "notes"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom="`connections` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 0;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 0;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 100;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "connections_view.php";
	$x->RedirectAfterInsert = "connections_view.php?SelectedID=#ID#";
	$x->TableTitle = "Connection Log";
	$x->TableIcon = "table.gif";
	$x->PrimaryKey = "`connections`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("TimeStamp", "Source IP", "Admin Key", "Target Port", "Exit Status", "Start Time", "End Time", "Notes");
	$x->ColFieldName = array('timestamp', 'sourceIP', 'adminkey', 'targetPort', 'exitStatus', 'startTime', 'endTime', 'notes');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 8, 9);

	$x->Template = 'templates/connections_templateTV.html';
	$x->SelectedTemplate = 'templates/connections_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `connections`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='connections' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `connections`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='connections' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`connections`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: connections_init
	$render=TRUE;
	if(function_exists('connections_init')){
		$args=array();
		$render=connections_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: connections_header
	$headerCode='';
	if(function_exists('connections_header')){
		$args=array();
		$headerCode=connections_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: connections_footer
	$footerCode='';
	if(function_exists('connections_footer')){
		$args=array();
		$footerCode=connections_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>